INSERT INTO planets
(name, description, population)
VALUES
("Burmecia-5","A quaint space station known for delicious food.",4188969),
("Shulva-Psi","A world that fell to catastophic climate change.",5796441),
("Dali-5","A small space station situated near a black hole.",2252645),
("Midgar-Rho","A space ship graveyard inhabited by outlaws.",4325256),
("Gongaga-Phi","An ancient planet inhabited by a powerful humanoid species.",9951825),
("Cryon-Nu","A travelling food ship that is famous for its Ramen bowls.",8637770),
("Talaxia-Tau","A tropical planet where many species seem to vacation.",5608736),
("Bruma-4","A peaceful world inhabited by industrious people.",9153540),
("Talaxia-Xi","A merchant colony bustling with commerce.",4912887),
("Krypton-Kappa","A prison space station home to the worst of the worst.",4833383),
("Treno-Nu","A travelling food ship that is famous for its Ramen bowls.",7226015),
("Burmecia-Mu","A cloning facility that raises armies for the highest bidders.",6464183),
("Gallifrey-Nu","A bleak & sparsely inhabited world.",1105868),
("Gallifrey-Alpha","A toxic planet whos people have long since fled.",4093089),
("Glaxon-Rho","A weapons research station shielded from prying eyes.",6691039),
("Besaid-5","A volcanic planet. much of its surface is covered by magma.",5565512),
("Cryon-Kappa","A travelling food ship that is famous for its Ramen bowls.",5375285),
("Shulva-Eta","A dark & noxious planet. deadly spores blanket its surface.",5746658),
("Bevelle-5","The lush homeworld to a proud warrior race.",2035721),
("Luca-Phi","An ancient planet inhabited by a powerful humanoid species.",1981931),
("Izalith-2","A weapons research station shielded from prying eyes.",1100068),
("Mideel-1","A ruined wartorn planet. civil war has raged for generations.",3552418),
("Talaxia-6","An abandoned mining colony thats now home to space pirates.",1639350),
("Bruma-Gamma","A densely populated planet where everything is scarce.",13633),
("Erus-Psi","A ruined wartorn planet. civil war has raged for generations.",422862),
("Doth-Zeta","An abandoned mining colony thats now home to space pirates.",6549005),
("Guadosalam-5","A cloning facility that raises armies for the highest bidders.",8655449),
("Halcyon-9","A prison space station home to the worst of the worst.",6950803),
("Talara-Sigma","A bleak & sparsely inhabited world.",2452389),
("Junon-Epsilon","A toxic planet whos people have long since fled.",6754471),
("Guadosalam-9","A dry planet where life exists without moisture.",294076),
("Guadosalam-Tau","A beautiful tropical planet brimming with life.",301253),
("Bevelle-4","A bleak & sparsely inhabited world.",8767045),
("Erd-Zeta","A cloning facility that raises armies for the highest bidders.",4969173),
("Halcyon-Sigma","A mystical planet where beings with strange powers rule.",1374092),
("Nuna-Alpha","A world that fell to catastophic climate change.",1156458),
("Bleezor-Gamma","A derelict alien vessel drifting through space.",8850722),
("Silon-Theta","A technologically advanced world where energy is currency.",2112583),
("Elea-Mu","The seat of power to a terrible empire.",1932037),
("Izalith-Rho","A toxic planet whos people have long since fled.",2448409),
("Cleyra-Gamma","A dry planet where life exists without moisture.",401558),
("Iotov-Upsilon","An ancient planet inhabited by a powerful humanoid species.",2607544),
("Bevelle-Chi","A bleak & sparsely inhabited world.",3436341),
("Arda-Psi","A blue ocean planet. strange vessels glide over its surface.",3243556),
("Macalania-6","A merchant colony bustling with commerce.",8298988),
("Zanarkand-7","A beautiful tropical planet brimming with life.",419008),
("Nuna-Omicron","A tropical planet where many species seem to vacation.",457165),
("Erd-9","An aquatic planet. research stations lie below its waves.",1254654),
("Shulva-Chi","A storm ravaged world where it always rains.",2875811),
("Balamb-Omicron","A volcanic planet. much of its surface is covered by magma.",3152143),
("Mora-Phi","A beautiful tropical planet brimming with life.",1120836),
("Dali-Epsilon","A storm ravaged world where it always rains.",1945083),
("Midgar-Psi","The seat of power to a terrible empire.",3868919),
("Cainhurst-3","A bleak & sparsely inhabited world.",1992822),
("Guadosalam-Sigma","A tropical planet where many species seem to vacation.",1462552),
("Macalania-7","A volcanic planet. much of its surface is covered by magma.",4194132),
("Zanarkand-Pi","A volcanic planet. much of its surface is covered by magma.",7161069),
("Balamb-1","A lush forest planet brimming with wildlife.",8824788),
("Talaxia-Pi","An ancient planet inhabited by a powerful humanoid species.",6441514),
("Cainhurst-Epsilon","An aquatic planet. research stations lie below its waves.",5810384),
("Djose-Chi","An ancient planet inhabited by a powerful humanoid species.",1881416),
("Guadosalam-Epsilon","A peaceful planet with a highly religious population.",5189624),
("Doth-Beta","A volcanic planet. much of its surface is covered by magma.",8377104),
("Treno-3","A bleak & sparsely inhabited world.",4532646),
("Elea-1","A quaint space station known for delicious food.",570414),
("Glaxon-Delta","A blue ocean planet. strange vessels glide over its surface.",8527087),
("Cardassia-Eta","A peaceful planet with a highly religious population.",9389861),
("Macalania-9","A mysterious planet whos inhabitants have long died.",144717),
("Yharnam-Xi","A peaceful world inhabited by industrious people.",745864),
("Zanarkand-Nu","A tropical planet where many species seem to vacation.",3121940),
("Eleum-Epsilon","A world that fell to catastophic climate change.",349178),
("Halcyon-Gamma","An abandoned mining colony thats now home to space pirates.",4786438),
("Burmecia-6","A blue ocean planet. strange vessels glide over its surface.",9532467),
("Gongaga-Tau","A lush forest planet brimming with wildlife.",5639217),
("Eleum-Omega","A bleak & sparsely inhabited world.",8827081),
("Besaid-Tau","A dry planet where life exists without moisture.",3096239),
("Djose-Xi","A bleak & sparsely inhabited world.",3026260),
("Midgar-Upsilon","A volcanic planet. much of its surface is covered by magma.",8786986),
("Kepler-Nu","A cloning facility that raises armies for the highest bidders.",4758613),
("Lordran-Xi","A travelling food ship that is famous for its Ramen bowls.",7334692),
("Luca-Sigma","An ancient planet inhabited by a powerful humanoid species.",7429752),
("Doth-4","A gas giant surrounded by strange vessels.",2581099),
("Halcyon-Rho","A technologically advanced world where energy is currency.",9102237),
("Romulus-Sigma","A prison space station home to the worst of the worst.",9307454),
("Besaid-Nu","A blue ocean planet. strange vessels glide over its surface.",6807025),
("Corel-Iota","A frozen tundra planet. blizzards rage continuously.",7224983),
("Krypton-Eta","The ruined world of a once mighty civilization.",6495989),
("Corel-Zeta","A lush forest planet brimming with wildlife.",9865116),
("Corel-Gamma","A weapons research station shielded from prying eyes.",3162225),
("Kepler-Beta","A bustling mining planet rich with natural resources.",9296738),
("Cardassia-1","The seat of power to a terrible empire.",5171347),
("Dali-Epsilon","An ancient planet inhabited by a powerful humanoid species.",3184741),
("Dali-Delta","An ancient planet inhabited by a powerful humanoid species.",2866845),
("Talaxia-Omicron","A travelling food ship that is famous for its Ramen bowls.",1239376),
("Glaxon-Gamma","A volcanic planet. much of its surface is covered by magma.",5316819),
("Terra-Mu","The lush homeworld to a proud warrior race.",5974025),
("Treno-6","A massive trading outpost. many species do business here.",335672),
("Talaxia-Sigma","An ancient planet inhabited by a powerful humanoid species.",3192639),
("Kepler-Kappa","A toxic planet whos people have long since fled.",2556544),
("Erus-6","A massive trading outpost. many species do business here.",3145810),
("Erus-Zeta","A densely populated planet where everything is scarce.",1449433),
("Eleum-Omicron","The ruined world of a once mighty civilization.",7654161),
("Izalith-Iota","An ancient planet inhabited by a powerful humanoid species.",2779072),
("Gulug-Phi","An abandoned mining colony thats now home to space pirates.",4802579),
("Balamb-Psi","A dark & noxious planet. deadly spores blanket its surface.",4990301),
("Dali-4","A volcanic planet. much of its surface is covered by magma.",4094548),
("Zanarkand-Iota","A mystical planet where beings with strange powers rule.",2827837),
("Cryon-Zeta","A derelict alien vessel drifting through space.",5658876),
("Guadosalam-Xi","A mystical planet where beings with strange powers rule.",1413840),
("Talaxia-Zeta","A technologically advanced world where energy is currency.",3343174),
("Guadosalam-Omega","A toxic planet whos people have long since fled.",3897907),
("Mideel-Pi","A quaint space station known for delicious food.",8618487),
("Cybertron-Omicron","A gas giant surrounded by strange vessels.",3394573),
("Erus-Psi","A technologically advanced world where energy is currency.",8317743),
("Guadosalam-Beta","A technologically advanced world where energy is currency.",8274091),
("Burmecia-Omega","An aquatic planet. research stations lie below its waves.",7641951),
("Krypton-Kappa","A travelling food ship that is famous for its Ramen bowls.",5428027),
("Macalania-8","A bustling mining planet rich with natural resources.",9793625),
("Glaxon-Omega","A weapons research station shielded from prying eyes.",1296133),
("Luca-Xi","A massive trading outpost. many species do business here.",3662616),
("Nuna-Omega","A technologically advanced world where energy is currency.",3627158),
("Yharnam-1","A dry planet where life exists without moisture.",956660),
("Bleezor-5","An abandoned mining colony thats now home to space pirates.",2781980),
("Elea-1","A weapons research station shielded from prying eyes.",8901029),
("Mora-Delta","A mysterious planet whos inhabitants have long died.",925606),
("Mideel-Rho","A peaceful world inhabited by industrious people.",8238907),
("Wutai-Theta","A tropical planet where many species seem to vacation.",2220261),
("Wutai-Pi","A dry planet where life exists without moisture.",1906683),
("Kilika-Lambda","An abandoned mining colony thats now home to space pirates.",3079893),
("Gulug-8","A derelict alien vessel drifting through space.",2121057),
("Halcyon-Xi","A mysterious planet whos inhabitants have long died.",2091153),
("Macalania-Tau","A small space station situated near a black hole.",4274258),
("Luca-1","A derelict alien vessel drifting through space.",655585),
("Izalith-Xi","A dark & noxious planet. deadly spores blanket its surface.",6257837),
("Halcyon-Epsilon","A derelict alien vessel drifting through space.",5396367),
("Junon-5","A blue ocean planet. strange vessels glide over its surface.",678528),
("Izalith-6","The seat of power to a terrible empire.",3960352),
("Silon-3","A volcanic planet. much of its surface is covered by magma.",1837099),
("Talaxia-Upsilon","A volcanic planet. much of its surface is covered by magma.",9063252),
("Halcyon-Phi","A toxic planet whos people have long since fled.",5476941),
("Halcyon-6","An abandoned mining colony thats now home to space pirates.",3617386),
("Djose-Chi","A quaint space station known for delicious food.",6032203),
("Terra-Omega","A small brutal planet where only the strong survive.",2508560),
("Kilika-Omicron","An abandoned mining colony thats now home to space pirates.",1313009),
("Besaid-3","A massive trading outpost. many species do business here.",2373720),
("Talaxia-Chi","A mysterious planet whos inhabitants have long died.",8033029),
("Luca-Alpha","A mysterious planet whos inhabitants have long died.",6289259),
("Cybertron-Delta","A blue ocean planet. strange vessels glide over its surface.",8161357),
("Silon-1","A peaceful planet with a highly religious population.",2899074),
("Junon-Theta","A mysterious planet whos inhabitants have long died.",2412375),
("Djose-1","An abandoned mining colony thats now home to space pirates.",9597594),
("Cainhurst-Sigma","A cloning facility that raises armies for the highest bidders.",7208270),
("Kilika-6","An ancient planet inhabited by a powerful humanoid species.",8260556),
("Macalania-Chi","A dark & noxious planet. deadly spores blanket its surface.",1540266),
("Yharnam-Iota","A storm ravaged world where it always rains.",4867398),
("Talaxia-Epsilon","A blue ocean planet. strange vessels glide over its surface.",4929005),
("Drangleic-Phi","A small brutal planet where only the strong survive.",1078058),
("Midgar-Gamma","A lush forest planet brimming with wildlife.",5163228),
("Erus-1","A dark & noxious planet. deadly spores blanket its surface.",9306992),
("Macalania-Omicron","A mystical planet where beings with strange powers rule.",4617582),
("Mora-Rho","A small space station situated near a black hole.",3861087),
("Alexandria-6","A merchant colony bustling with commerce.",7252968),
("Mideel-2","A merchant colony bustling with commerce.",9626657),
("Krypton-Iota","A dark & noxious planet. deadly spores blanket its surface.",1981296),
("Kilika-7","An abandoned mining colony thats now home to space pirates.",5153706),
("Kilika-5","A gas giant surrounded by strange vessels.",4724546),
("Junon-Alpha","A tropical planet where many species seem to vacation.",1968955),
("Lordran-1","A densely populated planet where everything is scarce.",6137651),
("Halcyon-7","The ruined world of a once mighty civilization.",5297829),
("Cardassia-Beta","An aquatic planet. research stations lie below its waves.",2077781),
("Bleezor-6","A cloning facility that raises armies for the highest bidders.",901967),
("Balamb-Psi","A densely populated planet where everything is scarce.",8567990),
("Junon-1","A blue ocean planet. strange vessels glide over its surface.",7766634),
("Cryon-Omicron","An aquatic planet. research stations lie below its waves.",1955660),
("Alexandria-Mu","A travelling food ship that is famous for its Ramen bowls.",8558364),
("Drangleic-Beta","A dry planet where life exists without moisture.",5942336),
("Iotov-3","A small brutal planet where only the strong survive.",5682010),
("Izalith-Kappa","A frozen tundra planet. blizzards rage continuously.",7042423),
("Luca-Eta","A peaceful planet with a highly religious population.",3206477),
("Romulus-5","A world that fell to catastophic climate change.",8886024),
("Lordran-3","A cloning facility that raises armies for the highest bidders.",8089478),
("Cybertron-9","A storm ravaged world where it always rains.",9471279),
("Zanarkand-Delta","A weapons research station shielded from prying eyes.",7904405),
("Balamb-Xi","A densely populated planet where everything is scarce.",6111763),
("Nivion-Eta","A derelict alien vessel drifting through space.",9460976),
("Yharnam-Iota","An abandoned mining colony thats now home to space pirates.",230627),
("Yharnam-4","A prison space station home to the worst of the worst.",3145604),
("Erd-3","A frozen tundra planet. blizzards rage continuously.",7693005),
("Izalith-Zeta","A blue ocean planet. strange vessels glide over its surface.",1852134),
("Besaid-6","A ruined wartorn planet. civil war has raged for generations.",6798618),
("Zanarkand-Eta","A cloning facility that raises armies for the highest bidders.",7201553),
("Junon-Lambda","A massive trading outpost. many species do business here.",5257246),
("Shulva-4","A space ship graveyard inhabited by outlaws.",1943826),
("Macalania-Mu","A blue ocean planet. strange vessels glide over its surface.",4524611),
("Gongaga-5","The ruined world of a once mighty civilization.",9108612),
("Burmecia-Pi","A peaceful planet with a highly religious population.",116187),
("Romulus-Beta","A space ship graveyard inhabited by outlaws.",610551),
("Oolacile-6","A quaint space station known for delicious food.",3368821),
("Corel-Omega","A dark & noxious planet. deadly spores blanket its surface.",7843894),
("Bleezor-Theta","A peaceful world inhabited by industrious people.",7848752),
("Djose-3","A travelling food ship that is famous for its Ramen bowls.",9995803);