-- drop old table if it exists.
DROP TABLE IF EXISTS aliens;

-- create new table.
CREATE TABLE aliens (
    id INT PRIMARY KEY,
    name NVARCHAR(50) NOT NULL,
    description NVARCHAR(MAX) NOT NULL,
    health INT NOT NULL,
    armor INT NOT NULL,
    money INT NOT NULL
);

-- populate table with data.
INSERT INTO aliens
(id, name, description, health, armor, money)
VALUES
(0,'Dusk Cosmos','A cyborg more machine than person. She is ruthless and efficient.',10,3,412),
(1,'Adelbert God of Sunlight','A humanoid fighter from another dimension.',12,3,222),
(2,'Odo The Rock','A proud father and fierce protector of the planet.',12,3,328),
(3,'Snarf Coral','A fox starship pilot known for his bravery.',10,2,373),
(4,'Kira Alexandros','A strange dark creature. it wields powerful magic.',11,1,485),
(5,'Cloud Crescent','A strange dark creature. it wields powerful magic.',10,3,318),
(6,'SHODAN Carol','A fox starship pilot known for his bravery.',10,3,183),
(7,'Cloud Heartilly','The Father of Sunlight. he has sacrificed everything for power.',11,2,255),
(8,'Spock Lockhart','A twisted monster and the father of an unstoppable abyss.',9,3,181),
(9,'Mewtwo Purple','A flufy yellow creature that produces lightning when angry.',13,2,261),
(10,'Miles Nerys','An ancient horror. Revered by many as a God.',12,2,271),
(11,'Spock Carol','A young girl and the last of her once powerful race.',13,1,440),
(12,'Barret Wallace','An ancient horror. Revered by many as a God.',12,3,447),
(13,'Seven Thundercat','A proud father and fierce protector of the planet.',9,3,330),
(14,'Seven Ketchum','A humanoid officer. Cold logical and highly intelligent.',9,3,187),
(15,'Sif Wallace','A humanoid fighter from another dimension.',9,1,217),
(16,'Artorias Cosmos','The Father of Sunlight. he has sacrificed everything for power.',9,2,362),
(17,'Marth Branford','A young girl and the last of her once powerful race.',12,2,239),
(18,'Celes Heartilly','The last of her kind. Hunted by many.',13,3,455),
(19,'Tifa of Catarina','A humanoid fighter from another dimension.',9,2,172),
(20,'Yuffie Alexandros','A legendary humanoid warrior. Known for facing impossible odds.',9,3,310),
(21,'Beatrix of Astora','A cyborg more machine than person. She is ruthless and efficient.',9,3,100),
(22,'Tifa Tribal','A test subject who can now transform into monstrous beasts.',10,3,422),
(23,'Spock Valentine','An ancient horror. Revered by many as a God.',10,1,327),
(24,'Barret of Oolacile','A humanoid officer. Cold logical and highly intelligent.',9,3,205),
(25,'Yuffie Purple','The personal knight to her king. Her strength has no equal.',11,1,479),
(26,'Thanos Prower','A fox starship pilot known for his bravery.',9,1,322),
(27,'Solaire XIII','A legendary humanoid warrior. Known for facing impossible odds.',9,3,206),
(28,'Amygdala Branford','An ancient horror. Revered by many as a God.',10,1,204),
(29,'Artorias Strife','A young mercenary bearing a large scar across his face.',12,2,144),
(30,'Leon Sith','A cyborg more machine than person. She is ruthless and efficient.',11,1,176),
(31,'Mewtwo of Catarina','A skilled thief who will do anything for the right price.',10,3,475),
(32,'Megatron Chere','A fox starship pilot known for his bravery.',13,1,302),
(33,'Seven Synthesis','A proud father and fierce protector of the planet.',13,3,162),
(34,'Rinoa Sith','A really cool guy.',9,1,292),
(35,'Gandalf Steiner','A mechanical zealot bent on domination at all costs.',12,2,173),
(36,'Siegward The Rock','A strange dark creature. it wields powerful magic.',12,1,386),
(37,'Spock Horror','A humanoid officer. Cold logical and highly intelligent.',13,1,155),
(38,'Garnet Heartilly','A small fury creature with a bag of mail over its shoulder.',10,2,311),
(39,'Tuvok Branford','A young girl and the last of her once powerful race.',12,3,334),
(40,'Eiko Valentine','A cat-like humanoid. Proud and strong; They will not falter.',12,1,393),
(41,'Tuvok Ketchum','A formidable dragoon knight wielding a ceremonial lance.',13,3,262),
(42,'Knuckles of Catarina','A giant black dragon. It has devoured countless souls.',12,1,103),
(43,'Rinoa Heartilly','A mechanical zealot bent on domination at all costs.',13,3,373),
(44,'Terra Ketchum','A strange dark creature. it wields powerful magic.',13,1,361),
(45,'Zidane the Hedgehog','A young girl and the last of her once powerful race.',11,3,271),
(46,'Kira Autobot','A humanoid clad in heavy stone plates. His defenses are legendary.',11,2,124),
(47,'Vivi Wallace','A humanoid fighter from another dimension.',11,3,270),
(48,'Gwyn Sith','A humanoid terrorist leader who rejects all authority but her own.',12,1,405),
(49,'Mewtwo Purple','A strange dark creature. it wields powerful magic.',13,2,102),
(50,'Jenova the White','A powerful warrior bent on achieving Godhood.',12,3,165),
(51,'Kuja Horror','A proud father and fierce protector of the planet.',9,2,246),
(52,'Kirby Carol','A small pudgy thing. it insults you mercilessly.',10,3,199),
(53,'Manus Decepticon','A plump humanoid who values honor (and beer) above all else.',10,2,128),
(54,'Ebrietas Father of Abyss','A formidable dragoon knight wielding a ceremonial lance.',12,3,371),
(55,'SHODAN Laren','An ace pilot with a foul mouth and a nicotine addiction.',13,2,322),
(56,'Liono Crescent','A scorned giant with many eyes and arms. It delights in torture.',13,1,333),
(57,'Manus Chere','A humanoid terrorist leader who rejects all authority but her own.',12,3,476),
(58,'Squall Valentine','The son of noble warrior.',11,2,274),
(59,'Marth Thundercat','An omnipotent AI. It will stop at nothing to impose its will.',10,3,438),
(60,'Red McCloud','A terrible evil. Ancients called it The Calamity From the Skies.',11,2,309),
(61,'Amygdala Purple','A pretty young woman accompanied by her dog.',9,2,399),
(62,'Beatrix Decepticon','A giant black dragon. It has devoured countless souls.',13,2,395),
(63,'Amygdala Horror','A skilled thief who will do anything for the right price.',10,2,203),
(64,'Gwyn Ornitier','The personal knight to her king. Her strength has no equal.',12,1,187),
(65,'Barret the Echidna','A humanoid clad in heavy stone plates. His defenses are legendary.',13,2,291),
(66,'Moogle the Grey','A flufy yellow creature that produces lightning when angry.',12,1,125),
(67,'Vincent Laren','A young girl and the last of her once powerful race.',9,3,489),
(68,'Squall Decepticon','A formidable dragoon knight wielding a ceremonial lance.',13,1,498),
(69,'Zell the Hedgehog','A shape shifter capable of fantastic feats when transformed.',12,1,372),
(70,'Artorias Highwind','A humanoid martial artist known for her beauty and strength.',10,1,198),
(71,'Red Carol','A humanoid clad in heavy stone plates. His defenses are legendary.',9,2,194),
(72,'Sif of Astora','A skilled thief who will do anything for the right price.',13,2,468),
(73,'Knuckles the Echidna','A shape shifter capable of fantastic feats when transformed.',11,2,475),
(74,'Mewtwo the Echidna','A princess pulled away from her own space and time.',11,2,350),
(75,'Mewtwo Crescent','An impulsive humanoid fighter known for his quick temper.',10,1,348),
(76,'Liono God of Sunlight','The son of noble warrior.',12,2,127),
(77,'Celes Purple','A cyborg more machine than person. She is ruthless and efficient.',12,3,325),
(78,'Liono Ornitier','A proud father and fierce protector of the planet.',11,2,385),
(79,'Gwyn XIII','A small pudgy thing. it insults you mercilessly.',13,2,164),
(80,'Gandalf Sith','A powerful humanoid ancient whos power knows no bounds.',9,3,151),
(81,'Pikachu Purple','A terrible evil. Ancients called it The Calamity From the Skies.',12,3,104),
(82,'Vincent Cosmos','An omnipotent AI. It will stop at nothing to impose its will.',13,2,217),
(83,'Amarant Greatwolf','An impulsive humanoid fighter known for his quick temper.',13,2,396),
(84,'Amarant Wallace','A twisted monster and the father of an unstoppable abyss.',9,2,149),
(85,'Siegward Father of Abyss','A young mercenary bearing a large scar across his face.',9,1,325),
(86,'Moogle Alexandros','A young mercenary bearing a large scar across his face.',10,1,268),
(87,'SHODAN Greatwolf','A formidable dragoon knight wielding a ceremonial lance.',10,1,433),
(88,'Freya Purple','A humanoid clad in heavy stone plates. His defenses are legendary.',10,3,380),
(89,'Adelbert Heartilly','A fox starship pilot known for his bravery.',12,3,295),
(90,'Vincent Coral','A test subject who can now transform into monstrous beasts.',12,1,331),
(91,'Zell Synthesis','A fox starship pilot known for his bravery.',9,3,105),
(92,'Zell Purple','The personal knight to her king. Her strength has no equal.',11,2,430),
(93,'Red Greatwolf','A scorned giant with many eyes and arms. It delights in torture.',9,3,102),
(94,'Jenova Steiner','A large humanoid driven mad and bent on destruction.',12,1,316),
(95,'Eiko Synthesis','An ace pilot with a foul mouth and a nicotine addiction.',11,3,353),
(96,'Megatron Laren','A noble knight who would give his life for his princess.',12,1,286),
(97,'Sif Heartilly','A plump humanoid who values honor (and beer) above all else.',10,3,393),
(98,'Tuvok Nerys','A pretty young woman accompanied by her dog.',10,2,366),
(99,'Leon the Dragonslayer','A skilled thief who will do anything for the right price.',13,1,300),
(100,'Artorias Chere','A large humanoid robot. A steadfast protecter of its kind.',11,2,489),
(101,'Starscream Coral','A humanoid clad in heavy stone plates. His defenses are legendary.',13,1,309),
(102,'Sephiroth Branford','A giant black dragon. It has devoured countless souls.',11,3,163),
(103,'Marth Dincht','A humanoid martial artist known for her beauty and strength.',9,2,422),
(104,'Leon One Winged Angel','An ancient horror. Revered by many as a God.',9,3,392),
(105,'Rinoa of Catarina','A powerful warrior bent on achieving Godhood.',12,1,193),
(106,'Knuckles the White','A plump humanoid who values honor (and beer) above all else.',10,3,289),
(107,'Amarant Lockhart','A princess who fled her kingdom to seek adventure.',13,2,200),
(108,'Celes Lionheart','A powerful warrior bent on achieving Godhood.',13,2,220),
(109,'Solaire Carol','A humanoid terrorist leader who rejects all authority but her own.',11,2,498),
(110,'Zell Strife','A large humanoid robot. A steadfast protecter of its kind.',11,1,108),
(111,'Ebrietas Tribal','A flufy yellow creature that produces lightning when angry.',12,2,381),
(112,'Thanos XIII','A massive wolf-like creature. It will die before it surrenders.',12,1,500),
(113,'Miles Smith','An ace pilot with a foul mouth and a nicotine addiction.',12,1,249),
(114,'Tuvok Coral','A cat-like humanoid. Proud and strong; They will not falter.',10,1,415),
(115,'SHODAN Tribal','A small pudgy thing. it insults you mercilessly.',11,1,367),
(116,'Rinoa of Astora','A small pudgy thing. it insults you mercilessly.',12,3,159),
(117,'Amygdala the Abysswalker','A leader to his people. His wisdom is known across the galaxy.',13,3,281),
(118,'Liono Carol','A humanoid freedom fighter from an occupied world.',11,1,418),
(119,'Manus the Dragon','The last of her kind. Hunted by many.',10,3,199),
(120,'Kira Carol','The humanoid captain of his lords knights. A fierce dragon slayer.',12,3,268),
(121,'Odo of Astora','A terrible evil. Ancients called it The Calamity From the Skies.',9,3,387),
(122,'Odo the Abysswalker','An omnipotent AI. It will stop at nothing to impose its will.',13,2,467),
(123,'Kalameet Laren','A scorned giant with many eyes and arms. It delights in torture.',13,1,466),
(124,'Squall Valentine','A fox starship pilot known for his bravery.',10,3,358),
(125,'Marth of Catarina','A small pudgy thing. it insults you mercilessly.',9,3,498),
(126,'Eiko Coral','A young girl and the last of her once powerful race.',12,2,461),
(127,'Rinoa Ketchum','The humanoid captain of his lords knights. A fierce dragon slayer.',12,1,499),
(128,'Dusk the Echidna','A large humanoid robot. A steadfast protecter of its kind.',10,3,333),
(129,'Liono Ketchum','An impulsive humanoid fighter known for his quick temper.',12,3,157),
(130,'Gandalf Valentine','A large humanoid driven mad and bent on destruction.',9,1,315),
(131,'Adelbert Wallace','A leader to his people. His wisdom is known across the galaxy.',12,1,158),
(132,'Siegward the Dragonslayer','A skilled thief who will do anything for the right price.',10,3,196),
(133,'Vincent Autobot','A test subject who can now transform into monstrous beasts.',9,3,491),
(134,'Mog Kupo','A cat-like humanoid. Proud and strong; They will not falter.',12,1,166),
(135,'Ro Laren','The Father of Sunlight. he has sacrificed everything for power.',12,2,263),
(136,'Mewtwo Smith','A terrible evil. Ancients called it The Calamity From the Skies.',12,1,210),
(137,'Manus Greatwolf','An ancient horror. Revered by many as a God.',10,3,410),
(138,'Tifa Cosmos','A small fury creature with a bag of mail over its shoulder.',9,2,494),
(139,'Roger the Abysswalker','A humanoid martial artist known for her beauty and strength.',9,3,304),
(140,'Leon Valentine','A really cool guy.',12,2,107),
(141,'Ro Carol','The last of her kind. Hunted by many.',12,2,335),
(142,'Garnet Horror','The personal knight to her king. Her strength has no equal.',9,2,325),
(143,'Kuja Purple','An omnipotent AI. It will stop at nothing to impose its will.',10,3,404),
(144,'Squall Steiner','The personal knight to her king. Her strength has no equal.',12,2,172),
(145,'Starscream Synthesis','An ancient horror. Revered by many as a God.',12,2,198),
(146,'Kirby the Hedgehog','The Father of Sunlight. he has sacrificed everything for power.',12,2,439),
(147,'Pikachu God of Sunlight','A proud father and fierce protector of the planet.',9,2,278),
(148,'Siegward Carol','A test subject who can now transform into monstrous beasts.',11,2,230),
(149,'Marth of Catarina','A giant black dragon. It has devoured countless souls.',13,1,140),
(150,'Moogle Laren','A legendary humanoid warrior. Known for facing impossible odds.',9,2,465),
(151,'Megatron Ketchum','A noble knight who would give his life for his princess.',10,3,219),
(152,'Zidane XIII','A shape shifter capable of fantastic feats when transformed.',9,1,390),
(153,'Miles the Grey','A terrible evil. Ancients called it The Calamity From the Skies.',13,1,305),
(154,'Gwyn Thundercat','The son of noble warrior.',12,1,205),
(155,'Terra the Abysswalker','A flufy yellow creature that produces lightning when angry.',11,3,422),
(156,'Tuvok of Astora','A small furry creaure. It frequently repeats its own name.',11,2,292),
(157,'Zell Coral','A powerful warrior bent on achieving Godhood.',13,1,140),
(158,'Ebrietas One Winged Angel','The personal knight to her king. Her strength has no equal.',10,2,315),
(159,'Mog Lionheart','The son of noble warrior.',12,1,320),
(160,'Vivi the Grey','A leader to his people. His wisdom is known across the galaxy.',13,1,432),
(161,'Beatrix Kupo','A humanoid martial artist known for her beauty and strength.',10,3,422),
(162,'Odo the White','A proud father and fierce protector of the planet.',10,3,367),
(163,'Amarant the Abysswalker','The personal knight to her king. Her strength has no equal.',12,1,190),
(164,'Manus the Abysswalker','A large humanoid robot. A steadfast protecter of its kind.',12,3,139),
(165,'Knuckles Carol','A massive wolf-like creature. It will die before it surrenders.',13,3,118),
(166,'Ro Heartilly','A mechanical zealot bent on domination at all costs.',9,3,417),
(167,'Seven Chere','A large humanoid driven mad and bent on destruction.',9,2,441),
(168,'Adelbert XIII','A powerful warrior bent on achieving Godhood.',12,3,250),
(169,'Sonic the Echidna','A terrible evil. Ancients called it The Calamity From the Skies.',11,3,263),
(170,'Megatron Alexandros','A shape shifter capable of fantastic feats when transformed.',12,3,226),
(171,'Solaire Greatwolf','A terrible evil. Ancients called it The Calamity From the Skies.',13,3,224),
(172,'Vincent Ornitier','A noble knight who would give his life for his princess.',12,1,495),
(173,'Artorias Smith','A legendary humanoid warrior. Known for facing impossible odds.',10,2,116),
(174,'Kira McCloud','A mechanical zealot bent on domination at all costs.',11,1,409),
(175,'Rinoa The Rock','A humanoid clad in heavy stone plates. His defenses are legendary.',13,3,456),
(176,'Marth XIII','A really cool guy.',13,3,443),
(177,'Tuvok the Echidna','A scorned giant with many eyes and arms. It delights in torture.',13,1,391),
(178,'Celes Greatwolf','A fox starship pilot known for his bravery.',12,3,480),
(179,'Optimus Cosmos','A formidable dragoon knight wielding a ceremonial lance.',10,3,259),
(180,'Celes Lockhart','An omnipotent AI. It will stop at nothing to impose its will.',11,1,472),
(181,'Amygdala Sith','A scorned giant with many eyes and arms. It delights in torture.',11,3,356),
(182,'Cloud Thundercat','A completely normal gambling robot.',11,1,455),
(183,'Optimus the Grey','A terrible evil. Ancients called it The Calamity From the Skies.',10,2,149),
(184,'Yuffie Prower','A mechanical zealot bent on domination at all costs.',13,1,468),
(185,'Miles Valentine','A pretty young woman accompanied by her dog.',12,2,266),
(186,'Barret Decepticon','The personal knight to her king. Her strength has no equal.',13,1,428),
(187,'Megatron Tribal','An impulsive humanoid fighter known for his quick temper.',12,1,402),
(188,'Artorias of Astora','A proud father and fierce protector of the planet.',13,3,269),
(189,'Havel Autobot','A young girl and the last of her once powerful race.',13,2,484),
(190,'Odo Highwind','A humanoid fighter from another dimension.',9,2,132),
(191,'Sephiroth Kupo','A massive wolf-like creature. It will die before it surrenders.',10,1,393),
(192,'Beatrix of Catarina','The Father of Sunlight. he has sacrificed everything for power.',11,2,339),
(193,'Leon Horror','A powerful humanoid ancient whos power knows no bounds.',12,3,274),
(194,'Tuvok the Hedgehog','A massive wolf-like creature. It will die before it surrenders.',9,1,348),
(195,'Kirby Smith','An impulsive humanoid fighter known for his quick temper.',11,3,269),
(196,'Kira the Dragonslayer','A completely normal gambling robot.',13,1,265),
(197,'Mewtwo the Echidna','A mechanical zealot bent on domination at all costs.',12,1,107),
(198,'Pikachu Prower','A mechanical zealot bent on domination at all costs.',9,1,349),
(199,'Spock McCloud','A giant black dragon. It has devoured countless souls.',10,3,160),
(200,'Kirby Lockhart','A princess pulled away from her own space and time.',13,1,329);