INSERT INTO planets
(name, description, population)
VALUES
("Eleum-Theta","The ruined world of a once mighty civilization.",6879628),
("Gallifrey-1","A volcanic planet. much of its surface is covered by magma.",6546516),
("Cardassia-7","A small brutal planet where only the strong survive.",6495928),
("Dali-Pi","A blue ocean planet. strange vessels glide over its surface.",3924276),
("Krypton-Delta","A prison space station home to the worst of the worst.",5009754),
("Mideel-Eta","A bleak & sparsely inhabited world.",4245248),
("Romulus-Eta","A weapons research station shielded from prying eyes.",5630386),
("Iotov-Theta","A volcanic planet. much of its surface is covered by magma.",2054216),
("Dali-Alpha","A beautiful tropical planet brimming with life.",4048870),
("Kilika-Lambda","A blue ocean planet. strange vessels glide over its surface.",6097199),
("Talara-Phi","A blue ocean planet. strange vessels glide over its surface.",9801710),
("Gallifrey-Upsilon","A cloning facility that raises armies for the highest bidders.",3208565),
("Shulva-Omega","A lush forest planet brimming with wildlife.",4051995),
("Cainhurst-Phi","A beautiful tropical planet brimming with life.",5577063),
("Mideel-6","The ruined world of a once mighty civilization.",6908864),
("Glaxon-7","A peaceful planet with a highly religious population.",7917849),
("Nuna-Lambda","A storm ravaged world where it always rains.",801585),
("Cybertron-Mu","A world that fell to catastophic climate change.",7315310),
("Drangleic-Upsilon","An ancient planet inhabited by a powerful humanoid species.",104277),
("Gulug-7","A dry planet where life exists without moisture.",4682691),
("Oolacile-Zeta","The ruined world of a once mighty civilization.",810762),
("Bruma-Kappa","A dark & noxious planet. deadly spores blanket its surface.",297237),
("Glaxon-Upsilon","A volcanic planet. much of its surface is covered by magma.",6792086),
("Mideel-5","A densely populated planet where everything is scarce.",4204220),
("Nivion-Mu","A peaceful world inhabited by industrious people.",5639395),
("Glaxon-Epsilon","A cloning facility that raises armies for the highest bidders.",1070149),
("Corel-Delta","A mystical planet where beings with strange powers rule.",9575709),
("Eleum-Phi","A gas giant surrounded by strange vessels.",3299047),
("Cainhurst-3","A peaceful planet with a highly religious population.",2087510),
("Talaxia-Tau","An abandoned mining colony thats now home to space pirates.",9485539),
("Erus-Lambda","A toxic planet whos people have long since fled.",6388606),
("Shulva-Omega","A small space station situated near a black hole.",5160447),
("Talaxia-Psi","A merchant colony bustling with commerce.",7809144),
("Romulus-Upsilon","A dry planet where life exists without moisture.",5130726),
("Terra-1","A blue ocean planet. strange vessels glide over its surface.",5213947),
("Luca-Sigma","A lush forest planet brimming with wildlife.",7043921),
("Nuna-3","A mystical planet where beings with strange powers rule.",8372118),
("Cardassia-Zeta","A peaceful planet with a highly religious population.",6877134),
("Djose-1","A massive trading outpost. many species do business here.",4563089),
("Glaxon-Xi","A bleak & sparsely inhabited world.",3461579),
("Doth-1","A toxic planet whos people have long since fled.",241387),
("Arda-Chi","An ancient planet inhabited by a powerful humanoid species.",6295149),
("Treno-Upsilon","A dry planet where life exists without moisture.",3083843),
("Talara-2","A tropical planet where many species seem to vacation.",6992611),
("Gallifrey-Phi","A space ship graveyard inhabited by outlaws.",1532998),
("Djose-Theta","A gas giant surrounded by strange vessels.",964049),
("Glaxon-3","A dark & noxious planet. deadly spores blanket its surface.",5396520),
("Bleezor-Theta","A ruined wartorn planet. civil war has raged for generations.",9797793),
("Nuna-Zeta","A bustling mining planet rich with natural resources.",8309170),
("Cleyra-Epsilon","A small brutal planet where only the strong survive.",1596831),
("Talara-Theta","A small space station situated near a black hole.",8012961),
("Junon-Omega","A toxic planet whos people have long since fled.",3231334),
("Burmecia-5","A cloning facility that raises armies for the highest bidders.",5277300),
("Shulva-Pi","A beautiful tropical planet brimming with life.",6262141),
("Oolacile-Pi","A peaceful planet with a highly religious population.",2737501),
("Cybertron-Psi","A storm ravaged world where it always rains.",7297182),
("Gongaga-Mu","A bustling mining planet rich with natural resources.",1950708),
("Drangleic-Omicron","A storm ravaged world where it always rains.",2620643),
("Cainhurst-Omega","A bustling mining planet rich with natural resources.",4733471),
("Wutai-1","A dry planet where life exists without moisture.",398212),
("Izalith-Alpha","A mystical planet where beings with strange powers rule.",6584143),
("Bleezor-Epsilon","A storm ravaged world where it always rains.",8493177),
("Dali-Pi","A bustling mining planet rich with natural resources.",9664238),
("Nivion-Mu","A ruined wartorn planet. civil war has raged for generations.",1015269),
("Wutai-Pi","A quaint space station known for delicious food.",4982227),
("Silon-Iota","A travelling food ship that is famous for its Ramen bowls.",5850185),
("Cybertron-6","A small brutal planet where only the strong survive.",7808157),
("Lordran-Upsilon","A mystical planet where beings with strange powers rule.",4191895),
("Kepler-2","A small space station situated near a black hole.",1749810),
("Alexandria-9","A small space station situated near a black hole.",803092),
("Luca-9","The ruined world of a once mighty civilization.",6578657),
("Djose-9","A lush forest planet brimming with wildlife.",7069424),
("Cryon-6","A beautiful tropical planet brimming with life.",7184046),
("Besaid-7","A frozen tundra planet. blizzards rage continuously.",7093938),
("Nivion-Epsilon","An abandoned mining colony thats now home to space pirates.",753939),
("Erd-Alpha","The seat of power to a terrible empire.",4197171),
("Kilika-Omega","A volcanic planet. much of its surface is covered by magma.",2299263),
("Erus-Gamma","A merchant colony bustling with commerce.",1376739),
("Glaxon-7","A merchant colony bustling with commerce.",8024888),
("Balamb-Nu","A space ship graveyard inhabited by outlaws.",3815912),
("Erd-2","A weapons research station shielded from prying eyes.",4621604),
("Balamb-2","A space ship graveyard inhabited by outlaws.",9964752),
("Cybertron-Mu","A cloning facility that raises armies for the highest bidders.",6133250),
("Alexandria-Tau","A tropical planet where many species seem to vacation.",8843004),
("Gongaga-4","A volcanic planet. much of its surface is covered by magma.",1129589),
("Shulva-1","A blue ocean planet. strange vessels glide over its surface.",4570256),
("Dali-Nu","A travelling food ship that is famous for its Ramen bowls.",5199071),
("Cleyra-Omicron","A space ship graveyard inhabited by outlaws.",1306133),
("Halcyon-Eta","A world that fell to catastophic climate change.",5687202),
("Talara-Nu","A toxic planet whos people have long since fled.",5532489),
("Cardassia-Chi","A weapons research station shielded from prying eyes.",1233834),
("Erus-Iota","A small brutal planet where only the strong survive.",4295631),
("Glaxon-2","A volcanic planet. much of its surface is covered by magma.",5265531),
("Eleum-Nu","A cloning facility that raises armies for the highest bidders.",3430303),
("Kepler-Epsilon","A frozen tundra planet. blizzards rage continuously.",6308693),
("Talaxia-Xi","A quaint space station known for delicious food.",3179325),
("Glaxon-Delta","A blue ocean planet. strange vessels glide over its surface.",5137169),
("Krypton-Phi","A gas giant surrounded by strange vessels.",9107241),
("Doth-Xi","A travelling food ship that is famous for its Ramen bowls.",3570831),
("Nivion-Psi","A densely populated planet where everything is scarce.",2297545),
("Drangleic-Kappa","A ruined wartorn planet. civil war has raged for generations.",120981),
("Cybertron-Xi","A derelict alien vessel drifting through space.",4603387),
("Nivion-8","A bustling mining planet rich with natural resources.",4975506),
("Luca-Rho","An abandoned mining colony thats now home to space pirates.",4585597),
("Mora-Tau","The ruined world of a once mighty civilization.",6973947),
("Shulva-9","A space ship graveyard inhabited by outlaws.",5784733),
("Treno-3","A prison space station home to the worst of the worst.",1473770),
("Arda-9","A weapons research station shielded from prying eyes.",9545410),
("Junon-Nu","A derelict alien vessel drifting through space.",699158),
("Romulus-Xi","A blue ocean planet. strange vessels glide over its surface.",2047926),
("Oolacile-7","A cloning facility that raises armies for the highest bidders.",1800984),
("Cardassia-7","A peaceful planet with a highly religious population.",3704106),
("Junon-Lambda","A bleak & sparsely inhabited world.",5561303),
("Macalania-2","A mysterious planet whos inhabitants have long died.",9210140),
("Izalith-Gamma","A dry planet where life exists without moisture.",298076),
("Cybertron-Omicron","A storm ravaged world where it always rains.",5340132),
("Junon-4","A quaint space station known for delicious food.",4523876),
("Junon-Iota","The seat of power to a terrible empire.",1327146),
("Glaxon-Upsilon","A volcanic planet. much of its surface is covered by magma.",3237719),
("Alexandria-Upsilon","A peaceful world inhabited by industrious people.",9496716),
("Zanarkand-Sigma","A technologically advanced world where energy is currency.",9480959),
("Nivion-Lambda","A peaceful world inhabited by industrious people.",8472631),
("Luca-Lambda","A travelling food ship that is famous for its Ramen bowls.",3620766),
("Izalith-6","A quaint space station known for delicious food.",8212968),
("Cryon-Pi","A massive trading outpost. many species do business here.",9349410),
("Junon-Chi","A dark & noxious planet. deadly spores blanket its surface.",674901),
("Guadosalam-Sigma","A weapons research station shielded from prying eyes.",8976594),
("Eleum-Phi","A travelling food ship that is famous for its Ramen bowls.",17266),
("Erus-Psi","A toxic planet whos people have long since fled.",8099343),
("Kilika-Kappa","A derelict alien vessel drifting through space.",3868596),
("Drangleic-Alpha","A merchant colony bustling with commerce.",6545703),
("Cardassia-Omega","A weapons research station shielded from prying eyes.",2024447),
("Gongaga-Tau","An aquatic planet. research stations lie below its waves.",6303920),
("Talara-Upsilon","A merchant colony bustling with commerce.",7400368),
("Bleezor-Chi","A mysterious planet whos inhabitants have long died.",7503951),
("Doth-Sigma","A derelict alien vessel drifting through space.",8852520),
("Kilika-Rho","A dry planet where life exists without moisture.",2202644),
("Izalith-Phi","The seat of power to a terrible empire.",8746455),
("Bevelle-Nu","A toxic planet whos people have long since fled.",4329559),
("Erus-9","A volcanic planet. much of its surface is covered by magma.",8513036),
("Gulug-9","A cloning facility that raises armies for the highest bidders.",7303909),
("Izalith-Nu","A bustling mining planet rich with natural resources.",1886509),
("Balamb-Omega","A space ship graveyard inhabited by outlaws.",2366140),
("Guadosalam-Theta","A weapons research station shielded from prying eyes.",3164202),
("Cybertron-Kappa","A bustling mining planet rich with natural resources.",7599983),
("Bevelle-Iota","A technologically advanced world where energy is currency.",9831790),
("Wutai-Lambda","A ruined wartorn planet. civil war has raged for generations.",4009399),
("Krypton-Mu","A merchant colony bustling with commerce.",810697),
("Zanarkand-Phi","A gas giant surrounded by strange vessels.",6540136),
("Besaid-7","A peaceful planet with a highly religious population.",7267814),
("Glaxon-Tau","A space ship graveyard inhabited by outlaws.",7345974),
("Djose-7","A bustling mining planet rich with natural resources.",5483306),
("Erus-Omega","A technologically advanced world where energy is currency.",9204721),
("Alexandria-Upsilon","A weapons research station shielded from prying eyes.",1847882),
("Gulug-Sigma","A beautiful tropical planet brimming with life.",9989274),
("Guadosalam-5","A quaint space station known for delicious food.",630165),
("Nuna-7","An ancient planet inhabited by a powerful humanoid species.",4872324),
("Guadosalam-8","A technologically advanced world where energy is currency.",4515977),
("Luca-7","A mystical planet where beings with strange powers rule.",1520441),
("Midgar-Tau","A weapons research station shielded from prying eyes.",3284749),
("Kilika-Gamma","A ruined wartorn planet. civil war has raged for generations.",4172256),
("Drangleic-Theta","A travelling food ship that is famous for its Ramen bowls.",6365566),
("Doth-Delta","A quaint space station known for delicious food.",7958732),
("Midgar-Gamma","A dark & noxious planet. deadly spores blanket its surface.",3583580),
("Kilika-Tau","A small brutal planet where only the strong survive.",2153686),
("Besaid-5","A dark & noxious planet. deadly spores blanket its surface.",2497513),
("Treno-Iota","A small space station situated near a black hole.",1276903),
("Wutai-Phi","A volcanic planet. much of its surface is covered by magma.",2365260),
("Macalania-1","A blue ocean planet. strange vessels glide over its surface.",1077547),
("Glaxon-3","A toxic planet whos people have long since fled.",676973),
("Oolacile-Psi","A weapons research station shielded from prying eyes.",8805454),
("Mora-Mu","A bustling mining planet rich with natural resources.",7733114),
("Gongaga-Upsilon","The ruined world of a once mighty civilization.",7518167),
("Talaxia-Zeta","A travelling food ship that is famous for its Ramen bowls.",9395980),
("Besaid-Nu","A massive trading outpost. many species do business here.",3800192),
("Guadosalam-1","A merchant colony bustling with commerce.",318654),
("Alexandria-Delta","A densely populated planet where everything is scarce.",390049),
("Kilika-Tau","A bleak & sparsely inhabited world.",1720931),
("Besaid-Sigma","The ruined world of a once mighty civilization.",2789409),
("Kilika-Theta","The seat of power to a terrible empire.",5849196),
("Talara-Alpha","A small space station situated near a black hole.",2927048),
("Nivion-2","An ancient planet inhabited by a powerful humanoid species.",4850136),
("Midgar-Xi","A dry planet where life exists without moisture.",9077523),
("Gongaga-Pi","A bleak & sparsely inhabited world.",7788028),
("Bleezor-9","A beautiful tropical planet brimming with life.",7104257),
("Cardassia-Sigma","A derelict alien vessel drifting through space.",4298877),
("Romulus-Sigma","A frozen tundra planet. blizzards rage continuously.",4604343),
("Glaxon-Xi","A bleak & sparsely inhabited world.",4427441),
("Gongaga-Upsilon","A storm ravaged world where it always rains.",1824837),
("Balamb-Xi","A massive trading outpost. many species do business here.",9706890),
("Shulva-Nu","A cloning facility that raises armies for the highest bidders.",9787566),
("Bleezor-5","A derelict alien vessel drifting through space.",5974344),
("Treno-Delta","A small brutal planet where only the strong survive.",7665757),
("Bleezor-Tau","A mysterious planet whos inhabitants have long died.",4709716),
("Kilika-Kappa","A gas giant surrounded by strange vessels.",944776),
("Cybertron-Phi","A small brutal planet where only the strong survive.",7891378),
("Erd-Iota","A derelict alien vessel drifting through space.",5632106),
("Cainhurst-4","A storm ravaged world where it always rains.",2711160),
("Bevelle-Upsilon","A travelling food ship that is famous for its Ramen bowls.",1205547),
("Doth-3","A mysterious planet whos inhabitants have long died.",778781),
("Eleum-Iota","A massive trading outpost. many species do business here.",3647783);